/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Años(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/20anos.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={3}>
      <group position={[0,-1.3, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.78, 0.1, 0.78]}>
        <mesh geometry={nodes.Tex.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Tex_1.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/20anos.gltf')
