/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Bombillo(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/area_interactive_01.gltf')
  return (
    <group ref={group} {...props} dispose={null} position={[0, 4.2, 0]} scale={0.7} rotation={[0, -2.2 , 0]}>
      <group position={[-1.32, 6.44, -3.01]} scale={[0.5, 0.5, 0.5]}>
        <mesh geometry={nodes['bombillobox-0-Bombillo007'].geometry} material={materials['Material.030']} />
        <mesh geometry={nodes['bombillobox-0-Bombillo007_1'].geometry} material={materials['Material.029']} />
        <mesh geometry={nodes['bombillobox-0-Bombillo007_2'].geometry} material={materials['Material.028']} />
        <mesh geometry={nodes['bombillobox-0-Bombillo007_3'].geometry} material={materials['Material.027']} />
        <mesh geometry={nodes['bombillobox-0-Bombillo007_4'].geometry} material={materials['Material.040']} />
        <mesh geometry={nodes['bombillobox-0-Bombillo007_5'].geometry} material={materials['Material.039']} />
        <mesh geometry={nodes['bombillobox-0-Bombillo007_6'].geometry} material={materials['Material.050']} />
        <mesh geometry={nodes['bombillobox-0-Bombillo007_7'].geometry} material={materials['Material.049']} />
        <mesh geometry={nodes['bombillobox-0-Bombillo007_8'].geometry} material={materials['Material.060']} />
        <mesh geometry={nodes['bombillobox-0-Bombillo007_9'].geometry} material={materials['Material.059']} />
      </group>
    </group>
  )
}

useGLTF.preload('/area_interactive_01.gltf')
