/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Lupa(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/area_procdeanalisis_01.gltf')
  return (
    <group ref={group} {...props} dispose={null} position={[-0.5, 4.2, 0]} scale={1.3}>
      <group position={[0.84, 0, 0.04]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes['LUPAMAG-0-lupa_1'].geometry} material={materials['Material.009']} />
        <mesh geometry={nodes['LUPAMAG-0-lupa_2'].geometry} material={materials['Material.010']} />
      </group>
      <group position={[0.77, 0, 0.04]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes['LUPAMAG-0-lupa001_1'].geometry} material={materials['Material.004']} />
        <mesh geometry={nodes['LUPAMAG-0-lupa001_2'].geometry} material={materials['Material.005']} />
        <mesh geometry={nodes['LUPAMAG-0-lupa001_3'].geometry} material={materials['Material.006']} />
        <mesh geometry={nodes['LUPAMAG-0-lupa001_4'].geometry} material={materials['Material.007']} />
        <mesh geometry={nodes['LUPAMAG-0-lupa001_5'].geometry} material={materials['Material.008']} />
      </group>
    </group>
  )
}

useGLTF.preload('/area_procdeanalisis_01.gltf')
