/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Guion(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/asig_guiones.gltf')
  return (
    <group ref={group} {...props} dispose={null} position={[-0.5, 4.5, 0]} scale={0.8}>
      <group position={[2.76, 2.09, 0]} scale={[1.06, 1.06, 0.88]}>
        <mesh geometry={nodes['carrete_vox-0-carrete001_1'].geometry} material={materials['Material.004']} />
        <mesh geometry={nodes['carrete_vox-0-carrete001_2'].geometry} material={materials['Material.001']} />
        <mesh geometry={nodes['carrete_vox-0-carrete001_3'].geometry} material={materials['Material.006']} />
        <mesh geometry={nodes['carrete_vox-0-carrete001_4'].geometry} material={materials['Material.009']} />
        <mesh geometry={nodes['carrete_vox-0-carrete001_5'].geometry} material={materials['Material.007']} />
        <mesh geometry={nodes['carrete_vox-0-carrete001_6'].geometry} material={materials['Material.008']} />
        <mesh geometry={nodes['carrete_vox-0-carrete001_7'].geometry} material={materials['Material.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/asig_guiones.gltf')
