/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Integra(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/asig_integra.gltf')
  return (
    <group ref={group} {...props} dispose={null} position={[0, 4.9, 0]} scale={0.75} rotation={[0, -1.6 , 0]}>
      <mesh geometry={nodes['antena_001-0-laptop_1'].geometry} material={materials['Material.001']} />
      <mesh geometry={nodes['antena_001-0-laptop_2'].geometry} material={materials['Material.002']} />
      <mesh geometry={nodes['antena_001-0-laptop_3'].geometry} material={materials['Material.003']} />
    </group>
  )
}

useGLTF.preload('/asig_integra.gltf')
