/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Guion(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/asig_guiones.gltf')
  return (
    <group ref={group} {...props} dispose={null} position={[0, 4.3, 0]} scale={0.8} >
      <mesh
        geometry={nodes['carrete_vox-0-carrete001'].geometry}
        material={materials['Material.004']}
        position={[1.91, 2.09, 0]}
        scale={[1.06, 1.06, 0.88]}
      />
      <mesh
        geometry={nodes['carrete_vox-0-carrete002'].geometry}
        material={materials['Material.001']}
        position={[0, 0, 2.29]}
      />
      <group position={[0, 0, -2.03]}>
        <mesh geometry={nodes['carrete_vox-0-carrete003_1'].geometry} material={materials['Material.006']} />
        <mesh geometry={nodes['carrete_vox-0-carrete003_2'].geometry} material={materials['Material.009']} />
      </group>
      <group position={[0, -15, 2.02]}>
        <mesh geometry={nodes['carrete_vox-0-carrete004_1'].geometry} material={materials['Material.007']} />
        <mesh geometry={nodes['carrete_vox-0-carrete004_2'].geometry} material={materials['Material.008']} />
      </group>
      <mesh
        geometry={nodes['carrete_vox-0-carrete005'].geometry}
        material={materials['Material.005']}
        position={[-1.92, 4.11, 0.02]}
        scale={[0.96, 0.96, 0.96]}
      />
    </group>
  )
}

useGLTF.preload('/asig_guiones.gltf')
