/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Libro(props) {
  
  const group = useRef()
  const { nodes, materials } = useGLTF('/asig_muleducativa_01.gltf')
  return (
    <group ref={group} {...props} dispose={null} position={[0.5,5.1,1]} scale={0.9}>
      <mesh
        geometry={nodes['librovoxel-0-LIBRO001'].geometry}
        material={materials['Material.001']}
        position={[-0.36, 2.39, -0.86]}
        rotation={[0.45, 0, 0]}
      />
      <mesh
        geometry={nodes['librovoxel-0-LIBRO002'].geometry}
        material={materials['Material.003']}
        position={[-0.36, 2.14, -1.01]}
        rotation={[0.45, 0, 0]}
      />
      <mesh
        geometry={nodes['librovoxel-0-LIBRO003'].geometry}
        material={materials['Material.002']}
        position={[-0.36, 1.89, -1.18]}
        rotation={[0.45, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/asig_muleducativa_01.gltf')
