/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Modelado(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/asig_model3d.gltf')
  return (
    <group ref={group} {...props} dispose={null} position={[-0.6,5,0]} scale={0.9}>
      <mesh geometry={nodes.monovox.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/asig_model3d.gltf')
