/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cerebro(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/asig_inteligencia_01.gltf')
  return (
    <group ref={group} {...props} dispose={null} position={[0, 4.5, 0]} rotation={[0, -1.6 , 0]} >
      <mesh geometry={nodes['CEREVTO-0-brain'].geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/asig_inteligencia_01.gltf')
