/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Tetera(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/asig_modelado3d_01.gltf')
  return (
    <group ref={group} {...props} dispose={null} position={[0,5.5,0]} scale={0.9}>
      <mesh geometry={nodes['teapodvox-0-TEApod'].geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/asig_modelado3d_01.gltf')
